services:
  # Backend NestJS
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: renaca-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./logs/backend:/app/logs
    networks:
      proxy:
        aliases:
          - renaca_backend
          - renaca-backend
      databases:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.renaca-backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.renaca-backend.entrypoints=websecure"
      - "traefik.http.routers.renaca-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.renaca-backend-http.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.renaca-backend-http.entrypoints=web"
      - "traefik.http.routers.renaca-backend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.renaca-backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.renaca-buffering.buffering.maxRequestBodyBytes=52428800"
      - "traefik.http.middlewares.renaca-buffering.buffering.maxResponseBodyBytes=52428800"
      - "traefik.http.routers.renaca-backend.middlewares=renaca-buffering@docker"
      - "traefik.http.routers.renaca-backend-http.middlewares=renaca-buffering@docker,redirect-to-https@docker"
      - "traefik.docker.network=proxy"

  # Frontend Vue.js
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: renaca-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.renaca-frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.renaca-frontend.entrypoints=websecure"
      - "traefik.http.routers.renaca-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.renaca-frontend-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.renaca-frontend-http.entrypoints=web"
      - "traefik.http.routers.renaca-frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.renaca-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
  databases:
    external: true